"""Constants for the Quant Screener pipeline."""

DEFAULT_TOP_K: int = 300
DEFAULT_TOP_N: int = 30
DEFAULT_UNIVERSE_SIZE: int = 4800

METADATA_MAX_CONCURRENCY: int = 1
METADATA_MIN_INTERVAL_S: float = 1
METADATA_MAX_RETRIES: int = 3
METADATA_RETRY_BACKOFF_S: float = 1.0
METADATA_FETCH_MAX_RETRIES: int = 2
FINANCIAL_MAX_CONCURRENCY: int = 1
FINANCIAL_MIN_INTERVAL_S: float = 1
FINANCIAL_FETCH_MAX_RETRIES: int = 2
PRICE_HISTORY_MAX_RETRIES: int = 2

DATA_DIR_NAME: str = "data"
RUNS_DIR_NAME: str = "runs"
EVIDENCE_DIR_NAME: str = "evidence"
LOGIC_GRAPH_DIR_NAME: str = "logic_graph"
REPORTS_DIR_NAME: str = "reports"
